- id: '1572624617150'
  alias: chambre ruban
  description: ''
  trigger:
  - device_id: af591a37ee134702bba1e6eea1815d1e
    domain: binary_sensor
    entity_id: binary_sensor.presence_2
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: motion
  action:
  - data:
      brightness: 150
      entity_id:
      - light.ruban
      rgb_color:
      - 255
      - 0
      - 0
    service: light.turn_on
- id: '1572629287512'
  alias: salon test ouverture
  description: ''
  trigger:
  - device_id: c4648785b645443280f6ff6e8f09b145
    domain: binary_sensor
    entity_id: binary_sensor.openclose_6
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: not_opened
  action:
  - device_id: d09efc8d30a84dadbceb5a4eb2c7f41c
    domain: light
    entity_id: light.hue_go_2
    type: turn_on
- id: '1572629893373'
  alias: ferme
  description: ''
  trigger:
  - device_id: c4648785b645443280f6ff6e8f09b145
    domain: binary_sensor
    entity_id: binary_sensor.openclose_6
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: opened
  condition: []
  action:
  - device_id: d09efc8d30a84dadbceb5a4eb2c7f41c
    domain: light
    entity_id: light.hue_go_2
    type: turn_off
