default_config:

############################################################
##                                                        ##
##                     HOME ASSISTANT                     ##
##                                                        ##
############################################################
homeassistant:
  name: !secret HA_NAME

  latitude: !secret HA_LAT
  longitude: !secret HA_LONG
  elevation: 39

  unit_system: metric
  time_zone: Europe/Paris

  customize: !include customize.yaml
  # javascript_version: latest

############################################################
##                                                        ##
##                        LOVELACE                        ##
##                                                        ##
############################################################
lovelace:
  mode: yaml

############################################################
##                                                        ##
##                      FRONTEND                          ##
##                                                        ##
############################################################
frontend:
  themes: !include_dir_merge_named themes

############################################################
##                                                        ##
##                     Hue pont                           ##
##                                                        ##
############################################################
hue:
  bridges:
    - host: !secret HUE_BRIDGE_IP
      allow_unreachable: true
      allow_hue_groups: true

############################################################
##                                                        ##
##                     influxdb                           ##
##                                                        ##
############################################################
influxdb:
  host: !secret INFLUXDB_IP
  port: !secret INFLUXDB_PORT
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

############################################################
##                                                        ##
##                     service                            ##
##                                                        ##
############################################################
tts:
  - platform: google_translate
    language: 'fr'

############################################################
##                                                        ##
##                     Capteur Linky                      ##
##                                                        ##
############################################################
linky:
  - username: !secret GMAIL
    password: !secret LINKY_PWD

############################################################
##                                                        ##
##                     notify                             ##
##                                                        ##
############################################################
# notify:
#   - name: NOTIFIER_NAME
#     platform: pushbullet
#     api_key: !secret PUSHBULLET_KEY  

############################################################
##https://community.home-assistant.io/t/easily-send-home-assistant-notifications-using-whatsapp/94072/19
##                     notify                             ##
##                     whatsapp                           ##
############################################################
# notify:
#   - name: whatsapp
#     platform: twilio_whatsapp
#     from_number: !secret TWILIO_NUMBER
#     account_sid: !secret TWILIO_ACCOUNT_SID
#     auth_token: !secret TWILIO_AUTH_TOKEN   

ffmpeg:

# http://automatedhome.party/2017/12/18/modify-the-xiaomi-xiaofang-camera-to-work-with-home-assistant-and-other-video-recording-software/
camera:
  - platform: ffmpeg
    name: Garage Cam
    input: rtsp://192.168.1.160:554/unicast


freebox:
  host: 347sywzf.fbxos.fr
  port: 41268


############################################################
##                                                        ##
##                     INCLUDE YAML                       ##
##                                                        ##
############################################################
group: !include groups.yaml
light: !include lights.yaml
automation: !include automations.yaml
sensor: !include sensor.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml
history: !include history.yaml
zone: !include zones.yaml
plant: !include plants.yaml
logbook: !include logbook.yaml
device_tracker: !include device_tracker.yaml
# ffmpeg: !include cameras.yaml
# person: !include persons.yaml
# snmp: !include snmp_bandwidth.yaml