default_config:

############################################################
##                                                        ##
##                     HOME ASSISTANT                     ##
##                                                        ##
############################################################

homeassistant:
  name: !secret HA_NAME

  latitude: !secret HA_LAT
  longitude: !secret HA_LONG
  elevation: 39

  unit_system: metric
  time_zone: Europe/Paris

  customize: !include customize.yaml
############################################################
##                                                        ##
##                        LOVELACE                        ##
##                                                        ##
############################################################
lovelace:
  mode: yaml

############################################################
##                                                        ##
##                      FRONTEND                          ##
##                                                        ##
############################################################
frontend:
  themes: !include_dir_merge_named themes

############################################################
##                                                        ##
##                     Hue pont                           ##
##                                                        ##
############################################################
hue:
  bridges:
    - host: !secret HUE_BRIDGE_IP
      allow_unreachable: true
      allow_hue_groups: false

############################################################
##                                                        ##
##                     influxdb                           ##
##                                                        ##
############################################################
influxdb:
  host: !secret INFLUXDB_IP
  port: !secret INFLUXDB_PORT
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

############################################################
##                                                        ##
##                     ????????                           ##
##                                                        ##
############################################################
tts:
  - platform: google_translate
    language: 'fr'
############################################################
##                                                        ##
##                     INCLUDE YAML                       ##
##                                                        ##
############################################################
group: !include groups.yaml
light: !include lights.yaml
automation: !include automations.yaml
sensor: !include sensor.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml
history: !include history.yaml
zone: !include zones.yaml
# person: !include persons.yaml
plant: !include plants.yaml
logbook: !include logbook.yaml
# snmp: !include snmp_bandwidth.yaml