title: My connect Home

resources:
  # pour des card avec graph
  - url: /local/mini-graph-card-bundle.js?v=0.8.1
    type: module

  # pour le module suivis des colis
  - url: /local/aftership-card.js
    type: module

  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module

  # pour des card la meteo 
  - url: /local/custom-lovelace/weather-card/weather-dark-sky-card.js?v=7.015
    type: module

views:

  - icon: mdi:forklift
    title: Second view
    path: home

    cards:
      - type: 'custom:aftership-card'
        entity: sensor.aftership
        title: Packages

  - icon: mdi:home-assistant
    title: Second view
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entities:
            - sensor.balcon
          line_color: blue
          line_width: 8
          font_size: 75
          color_thresholds:
          - value: 10
            color: "#33F0FF"
          - value: 20
            color: green
          - value: 30
            color: "#c0392b"
        - type: custom:mini-graph-card
          entities:
            - sensor.cuisine
          line_color: '#e74c3c'
          line_width: 8
        - type: custom:mini-graph-card
          entities:
            - sensor.chambre
          line_color: var(--accent-color)
          line_width: 8
          font_size: 75

      - type: light
        entity: light.ruban
        name: My Bed

      - type: custom:weather-card
        entity: weather.maison
        icons: "/local/custom-lovelace/weather-card/icones/animated/"
        name: Merignac
        # current: true
        # details: false
        # forecast: true


      - type: 'custom:dark-sky-weather-card'
        # entity_current_text: sensor.ozamiz_temperature
        # entity_current_conditions: sensor.sun_next
        entity_current_conditions: sensor.ozamiz_icon
        entity_temperature: sensor.ozamiz_temperature
        entity_forecast_high_temp_1: sensor.ozamiz_daytime_high_temperature_1d
        entity_forecast_high_temp_2: sensor.ozamiz_daytime_high_temperature_2d
        entity_forecast_high_temp_3: sensor.ozamiz_daytime_high_temperature_3d
        entity_forecast_high_temp_4: sensor.ozamiz_daytime_high_temperature_4d
        entity_forecast_high_temp_5: sensor.ozamiz_daytime_high_temperature_5d
        entity_forecast_icon_1: sensor.ozamiz_icon_1d
        entity_forecast_icon_2: sensor.ozamiz_icon_2d
        entity_forecast_icon_3: sensor.ozamiz_icon_3d
        entity_forecast_icon_4: sensor.ozamiz_icon_4d
        entity_forecast_icon_5: sensor.ozamiz_icon_5d
        entity_forecast_low_temp_1: sensor.ozamiz_overnight_low_temperature_0d
        entity_forecast_low_temp_2: sensor.ozamiz_overnight_low_temperature_1d
        entity_forecast_low_temp_3: sensor.ozamiz_overnight_low_temperature_2d
        entity_forecast_low_temp_4: sensor.ozamiz_overnight_low_temperature_3d
        entity_forecast_low_temp_5: sensor.ozamiz_overnight_low_temperature_4d
        entity_summary_1: sensor.ozamiz_summary_1d
        entity_summary_2: sensor.ozamiz_summary_2d
        entity_summary_3: sensor.ozamiz_summary_3d
        entity_summary_4: sensor.ozamiz_summary_4d
        entity_summary_5: sensor.ozamiz_summary_5d
        locale: en
        sunset: true

        entity_visibility: sensor.ozamiz_visibility
        # entity_daytime_high: sensor.ozamiz_daytime_high_temperature_0d
        entity_wind_bearing: sensor.ozamiz_wind_bearing
        entity_wind_speed: sensor.ozamiz_wind_speed
        entity_humidity: sensor.ozamiz_humidity
        entity_pressure: sensor.ozamiz_pressure
        entity_apparent_temp: sensor.ozamiz_apparent_temperature
        # entity_daily_summary: sensor.ozamiz_daily_summary

        # static_icons: false
        # tooltip_bg_color: 'rgb( 75,155,239)'
        # tooltip_border_color: orange
        # tooltip_border_width: 3
        # tooltip_caret_size: 10
        # tooltip_fg_color: '#fff'
        # tooltip_left_offset: -12
        # tooltip_width: 100
        # tooltips: true
        # old_daily_format: false
        # time_format: 12
        # show_beaufort: true