resources:
  # - !include lovelace/resources/modules.yaml
  - url: /local/mini-graph-card-bundle.js?v=0.8.1
    type: module

  # pour le module suivis des colis
  - url: /local/aftership-card.js
    type: module
  
title: My connect Home

views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_ge.yaml
  - !include lovelace/20_lights_view.yaml
