resources:
  # - !include lovelace/resources/modules.yaml
  - url: /local/custom-lovelace/mini-graph-card/mini-graph-card-bundle.js?v=0.9.2
    type: module 

  # https://github.com/iantrich/aftership-card
  # pour le module suivis des colis
  - url: /local/aftership-card.js
    type: module

  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module

  # pour des card la meteo 
  - url: /local/custom-lovelace/weather-card/weather-dark-sky-card.js?v=7.015
    type: module

  - url: /local/mini-media-player-bundle.js?v=1.4.2
    type: module    

  # https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /local/custom-lovelace/slider-entity-row/slider-entity-row.js
    type: module

title: Our smart home

views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_ge.yaml
  - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_asawa_ko.yaml
  - !include lovelace/40_all.yaml

