esphome:
  name: nodemcu_oled
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret IOT_SSID
  password: !secret IOT_PWD
  manual_ip:
    static_ip: 192.168.1.200
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: D1
  scl: D2

font:
  - file: "arial.ttf"
    id: my_font
    size: 10

  - file: 'digital-7.ttf'
    id: digital
    size: 25


time:
  - platform: homeassistant
    timezone: Europe/Paris
    id: sntp_time_fr
  # - platform: sntp
  #   timezone: Asia/Manila
  #   id: sntp_time_ph
    
sensor:
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.temperature_15
    internal: true

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.temperature_8
    internal: true
  
  - platform: homeassistant
    id: covid_french_current
    entity_id: sensor.france_coronavirus_confirmed
    internal: true

text_sensor:
  - platform: homeassistant
    id: worldclock_manila
    entity_id: sensor.manila
    internal: true

image:
  - file: "image.png"
    id: my_image
    resize: 100x100    
    
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    #reset_pin: D0
    address: 0x3C
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.print(0, 0, id(my_font), "Bordeaux");
          it.strftime(60, 11, id(digital), TextAlign::TOP_CENTER, "%H:%M", id(sntp_time_fr).now());
          it.print(0, 30, id(my_font), "Ozamiz");     
          it.printf(60, 44, id(digital), TextAlign::TOP_CENTER, "%s", id(worldclock_manila).state.c_str());      
      # - id: page2
      #   lambda: |-
      #     it.printf(0, 10, id(my_font), "The data is: %s", id(worldclock_manila).state.c_str());

      #    it.print(0, 10, id(my_font), "This is page 2!");
      # - id: page3
      #   lambda: |-          
      #     if (id(outside_temperature).state == id(outside_temperature).state) {
      #       it.printf(127, 23, id(my_font), TextAlign::TOP_RIGHT , "outside %.0f °C", id(outside_temperature).state);
      #     } else {
      #       it.print(127, 23, id(font3), TextAlign::TOP_RIGHT , "...waiting...");
      #     }
          
      #     if (id(inside_temperature).state == id(inside_temperature).state) {
      #       it.printf(127, 37, id(my_font), TextAlign::TOP_RIGHT , "inside %.0f °C", id(inside_temperature).state);
      #     } else {
      #       it.print(127, 37, id(font3), TextAlign::TOP_RIGHT , "...waiting...");
      #     }

      #     if (id(covid_french_current).state == id(covid_french_current).state) {
      #       it.printf(127, 50, id(my_font), TextAlign::TOP_RIGHT , "COVID-19 %.0f", id(covid_french_current).state);
      #     } else {
      #       it.print(127, 50, id(font3), TextAlign::TOP_RIGHT , "...waiting...");
      #     }  
    
interval:
  - interval: 5s
    then:
      - display.page.show_next: my_display
      - component.update: my_display      