esphome:
  name: nodemcu_oled
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret IOT_SSID
  password: !secret IOT_PWD
  fast_connect: true

  manual_ip:
    static_ip: 192.168.1.200
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: D1
  scl: D2

font:
  - file: "arial.ttf"
    id: arial_10
    size: 10
  - file: "arial.ttf"
    id: arial_14
    size: 14
  - file: "arial.ttf"
    id: arial_20
    size: 20
  - file: 'digital-7.ttf'
    id: digital
    size: 25

time:
  - platform: homeassistant
    timezone: Europe/Paris
    
sensor:
  # salon
  - platform: homeassistant
    id: temp_inside
    entity_id: sensor.temperature_15
    internal: true
  # dehors
  - platform: homeassistant
    id: temp_outside
    entity_id: sensor.temperature_8
    internal: true
  # debroom
  - platform: homeassistant
    id: temp_debroom
    entity_id: sensor.temperature_3
    internal: true
  # france_coronavirus_confirmed
  - platform: homeassistant
    id: covid_french_current
    entity_id: sensor.france_coronavirus_confirmed
    internal: true          
          
text_sensor:
  - platform: homeassistant
    id: worldclock_manila
    entity_id: sensor.worldclock_manila
    internal: true
  - platform: homeassistant
    id: worldclock_paris
    entity_id: sensor.worldclock_paris
    internal: true

# push alarm
# binary_sensor:
#   - platform: gpio
#     name: "Living Room Window"
#     pin:
#       number: 16
#       inverted: True
#       mode: INPUT_PULLUP

image:
  - file: "./img/mdi/bed-outline.png"
    id: mdi_bed
  - file: "./img/mdi/home-thermometer-outline.png"
    id: mdi_home
  - file: "./img/mdi/home-city-outline.png"
    id: mdi_city
  - file: "./img/mdi/virus.png"
    id: mdi_virus

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    #reset_pin: D0
    address: 0x3C
    id: my_display
    pages:
      # 
      # worldclock_paris & worldclock_manila
      # 
      - id: page1
        lambda: |-
          it.print(0, 0, id(arial_10), "Bordeaux");
          it.printf(60, 13, id(digital), TextAlign::TOP_CENTER, "%s", id(worldclock_paris).state.c_str());
          it.print(0, 30, id(arial_10), "Ozamiz");     
          it.printf(60, 44, id(digital), TextAlign::TOP_CENTER, "%s", id(worldclock_manila).state.c_str());
      # 
      # weather
      #      
      - id: page2
        lambda: |-
          it.image(0, 10, id(mdi_bed));
          it.printf(18, 46, id(arial_14), TextAlign::TOP_CENTER , "%.0f °C", id(temp_debroom).state);

          it.image(46, 10, id(mdi_home));
          it.printf(68, 46, id(arial_14), TextAlign::TOP_CENTER , "%.0f °C", id(temp_inside).state);

          it.image(92, 10, id(mdi_city));
          it.printf(110, 46, id(arial_14), TextAlign::TOP_CENTER , "%.0f °C", id(temp_outside).state);
      # 
      # extra (corona Virus)
      #
      - id: page3
        lambda: |-   
          it.image(0, 10, id(mdi_virus));   
          it.printf(74, 20, id(arial_20), TextAlign::TOP_CENTER , "%.0f", id(covid_french_current).state);
          it.print(68, 35, id(arial_20), TextAlign::TOP_CENTER , "cas");      

interval:
  - interval: 5s
    then:
      - display.page.show_next: my_display
      - component.update: my_display    