# Author by airijia.com
# ESP32-CAM
# Lovelace camera card https://github.com/custom-cards/camera-card
# Video tutorial https://youtu.be/-towjof_ixU
esphome:
  name: cam01
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret IOT_SSID
  password: !secret IOT_PWD
  fast_connect: True

  manual_ip:
    static_ip: 192.168.1.202
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    
    
api:
  reboot_timeout: 0s
ota:
logger:

# web_server:
#   port: 80
  
# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  name: ESP32CAM1
  # ... Frame Settings

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: $hostname light