esphome:
  name: nodeyellow
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "llm_domotique"
  password: "AV3iYuklyOySMXcRr2YVQRpXJ4X28mqIIt1pnkam9ZEV7qvyrTTIuJpDMMEU95l"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodeyellow Fallback Hotspot"
    password: "1JLwgRtQ8FXT"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
